---
title: "My-Pre-Registration"
output: html_document
bibliography: Preregistration.bib
csl: apa.csl
link-citations: true
editor_options: 
  markdown: 
    wrap: sentence
---

# Pre-registration Template

Adapted from <https://osf.io/preprints/metaarxiv/epgjd> into markdown
format.

<details>

-   [Study Information](#study-information)
    -   [1. Title](#1-title)
    -   [2. Authors](#2-authors)
    -   [3. Description](#3-description)
    -   [4. Hypotheses](#4-hypotheses)
-   [Design Plan](#design-plan)
    -   [5. Study type](#5-study-type)
    -   [6. Blinding](#6-blinding)
    -   [7. Is there any additional blinding in this
        study?](#7-is-there-any-additional-blinding-in-this-study-)
    -   [8. Study design](#8-study-design)
    -   [9. Randomization](#9-randomization)
-   [Sampling Plan](#sampling-plan)
    -   [10. Existing data](#10-existing-data)
    -   [11. Explanation of existing
        data](#11-explanation-of-existing-data)
    -   [12. Data collection procedures](#12-data-collection-procedures)
    -   [13. Sample size](#13-sample-size)
    -   [14. Sample size rationale](#14-sample-size-rationale)
    -   [15. Stopping rule](#15-stopping-rule)
-   [Variables](#variables)
    -   [16. Manipulated variables](#16-manipulated-variables)
    -   [17. Measured variables](#17-measured-variables)
    -   [18. Indices](#18-indices)
-   [Analysis Plan](#analysis-plan)
    -   [19. Statistical models](#19-statistical-models)
    -   [20. Transformations](#20-transformations)
    -   [21. Inference criteria](#21-inference-criteria)
    -   [22. Data exclusion](#22-data-exclusion)
    -   [23. Missing data](#23-missing-data)
    -   [24. Exploratory analysis](#24-exploratory-analysis)
-   [Other](#other)
    -   [25. Other](#25-other)

</details>

# Study Information {#study-information}

## 1. Title

> Title: Effect of background music on decision-making.

## 2. Authors

> Emily Duan

## 3. Description

> Arousal and valence are crucial factors in defining emotions in music.
> Modality in music often associate with valence, where minor often
> leads to negative energy and major often leads to positive energy.
> However, this does not apply to all cultures, as some region might
> have a opposing effect on valence. For example, the Indonesian
> participants in a cultural-specific study could only identify
> “happiness” and “sadness”, and were unable to identify other kinds of
> emotions instantly [@Argstatter2016]. Therefore we suspect valence
> would have less impact than arousal. Previous study done by Krahé and
> Bieneck (2012) has shown that pleasant music will induce positive
> mood, therefore reducing anger and less aggressive behaviours.
> Personality might be a important factor related to music preference, a
> study done on the Big Five Inventory personality traits has shown
> significant correlations between personality traits and genre
> preferences (Ferwerda et al., 2017), and high extroversion individuals
> tends to have a higher arousal level in both negative and positive
> valence cases (Kuppens et al., 2017). Arousal, different than valence,
> is a universal factor that shows a greater emotional convergence
> (Stevens et al., 2009). Tempo in music brings different levels of
> arousal (drowsy or awake) to people. We found that previous study has
> shown that faster music tempi elicited faster subsequent choice
> reaction time (CRT) performance (Bishop et al., 2009). Therefore, we
> are curious about how tempo and/or valence might have an effect on
> performances when it comes to making decisions. In this study, we will
> introduce fast-positive (excitement), fast-negative (anger),
> slow-positive (calm), and slow-negative (sad) music. A questionnaire
> will be filled after each trial, asking the pleasantness of these four
> types of music. This study aims to investigate whether background
> music influences risk-taking behavior in decision-making games.
> Process conflict positiively associates with excitement (Chen & Ayoko,
> 2012), If betrayal leads to anger (Joskowicz–Jabloner & Leiser, 2013),
> reversely, can anger trigger betrayal behaviours? Specifically, we
> hypothesize that fast-negative music (anger) may induce betrayal
> behaviours, while slow-positive music (calm) may promote cooperation.
> The study uses a repeating, decision-making game with varying
> background music. Participants will either have to choose "cooperate"
> or "betray" in rounds of games, playing with an opponent. Because the
> game is a process repeating themselves, it involves the Folk Theorem,
> where players know this game is going to play for more than once, they
> will more likely to choose "cooperate" even though they have the
> chance to betray, because betrayal could lead to a different outcome
> in the future. Participants' choices will be recorded and analyzed
> alongside self-reported mood responses to determine if music affects
> strategic decision-making. This study contributes to understanding how
> auditory stimuli impact emotions and subsequent social behaviours,
> with potential applications in psychology.

## 4. Hypotheses

> Null hypothesis (H0): Background music's tempo and modality do not
> have an affect on reaction time and the choice made in risk-taking
> task.

> (Directional) If background music's tempo affects reaction time, then
> faster tempo will lead to shorter mean reaction times during the
> risk-taking task.

> (Directional) If background music's tempo affects decision-making,
> then a faster tempo will result in participants choosing "betray" more
> often than "cooperate" in the risk-taking task.

> (Directional) If background music's modality (valence/energy level)
> affects reaction time, then negatively energized music (e.g.,
> fast-negative or slow-negative) will lead to shorter mean reaction
> times during the risk-taking task.

> (Directional) If background music's modality (valence/energy level)
> affects decision-making, then negatively energized music will lead to
> participants choosing "betray" more often than "cooperate" in the
> risk-taking task.

# Design Plan {#design-plan}

> In this section, you will be asked to describe the overall design of
> your study. Remember that this research plan is designed to register a
> single study, so if you have multiple experimental designs, please
> complete a separate preregistration.

## 5. Study type

> **Experiment** - A researcher randomly assigns treatments to study
> subjects, this includes field or lab experiments. This is also known
> as an intervention experiment and includes randomized controlled
> trials.

## 6. Blinding

> Blinding describes who is aware of the experimental manipulations
> within a study. Mark all that apply.

-   [ ] No blinding is involved in this study.

-   [x] For studies that involve human subjects, they will not know the
    treatment group to which they have been assigned.

-   [ ] Personnel who interact directly with the study subjects (either
    human or non-human subjects) will not be aware of the assigned
    treatments. (Commonly known as “double blind”)

-   [ ] Personnel who analyze the data collected from the study are not
    aware of the treatment applied to any given group.

## 7. Is there any additional blinding in this study?

> N/A

## 8. Study design

> We have a within-subjects (paired) factorial design with 2 factors:
> tempo (fast vs. slow) and modality (positive vs. negative), each with
> 2 levels, resulting in 4 conditions (fast-positive, fast-negative,
> slow-positive, slow-negative).

> Independent Variables (IVs): Tempo (Fast vs. Slow) Modality (Positive
> vs. Negative)

> Dependent Variables (DVs): Mean reaction time Decision outcome
> ("betray" vs. "cooperate")

> Since participants go through multiple conditions, counterbalancing
> like Latin square design or randomized order is needed to prevent
> order effects such as fatigue or learning.

## 9. Randomization

> We will use counterbalanced block randomization, where each
> participant will experience all four conditions (fast-positive,
> fast-negative, slow-positive, slow-negative) in a randomized order to
> minimize order effects.

> The random sequence assignments will be generated using computerized
> randomization (e.g., via Random.org). If sample size permits, we will
> use a Latin square design to ensure that each condition appears
> equally often in each position across participants.

# Sampling Plan {#sampling-plan}

> In this section we'll ask you to describe how you plan to collect
> samples, as well as the number of samples you plan to collect and your
> rationale for this decision. Please keep in mind that the data
> described in this section should be the actual data used for analysis,
> so if you are using a subset of a larger dataset, please describe the
> subset that will actually be used in your study.

## 10. Existing data

> Preregistration is designed to make clear the distinction between
> confirmatory tests, specified prior to seeing the data, and
> exploratory analyses conducted after observing the data. Therefore,
> creating a research plan in which existing data will be used presents
> unique challenges. Please select the description that best describes
> your situation. Please do not hesitate to contact us if you have
> questions about how to answer this question
> ([prereg\@cos.io](mailto:prereg@cos.io){.email}).

-   [x] Registration prior to creation of data: As of the date of
    submission of this research plan for preregistration, the data have
    not yet been collected, created, or realized.
-   [ ] Registration prior to any human observation of the data: As of
    the date of submission, the data exist but have not yet been
    quantified, constructed, observed, or reported by anyone - including
    individuals that are not associated with the proposed study.
    Examples include museum specimens that have not been measured and
    data that have been collected by non-human collectors and are
    inaccessible.
-   [ ] Registration prior to accessing the data: As of the date of
    submission, the data exist, but have not been accessed by you or
    your collaborators. Commonly, this includes data that has been
    collected by another researcher or institution.
-   [ ] Registration prior to analysis of the data: As of the date of
    submission, the data exist and you have accessed it, though no
    analysis has been conducted related to the research plan (including
    calculation of summary statistics). A common situation for this
    scenario when a large dataset exists that is used for many different
    studies over time, or when a data set is randomly split into a
    sample for exploratory analyses, and the other section of data is
    reserved for later confirmatory data analysis.
-   [ ] Registration following analysis of the data: As of the date of
    submission, you have accessed and analyzed some of the data relevant
    to the research plan. This includes preliminary analysis of
    variables, calculation of descriptive statistics, and observation of
    data distributions. Please see cos.io/prereg for more information.

## 11. Explanation of existing data

> There are no existing data for this study.

## 12. Data collection procedures

> Participants will be recruited from university student populations via
> email advertisements, flyers posted on campus, and course credit
> systems (e.g. SONA). No monetary compensation will be provided, but
> participants may receive a course credit or entry into a raffle for a
> small prize (e.g., a gift card).
>
> Inclusion rules: Age 18–30 years old, fluent in English (to understand
> instructions and questionnaires), and normal or corrected-to-normal
> vision and hearing (to perceive music and game elements accurately).
>
> Exclusion rules: Participants with formal musical training (to prevent
> guessing the blind conditions), and those who have previously
> participated in similar decision-based game studies (to avoid learned
> strategies and practice effect).
>
> Study timeline: Recruitment Period: within 1-2 months

## 13. Sample size

> Our target sample size is 64 participants to achieve adequate
> statistical power, considering the repeated measures design and
> expected effect sizes. We will recruit up to 80 participants to
> account for potential dropouts or incomplete data. The unit of
> analysis will be individual participants. Each participant will
> complete all four conditions (fast-positive, fast-negative,
> slow-positive, slow-negative). Data will be collected on reaction
> times and decision outcomes (cooperate vs. betray) for each condition.

## 14. Sample size rationale

> We will conduct a power analysis using Rstudio to determine the
> appropriate sample size for our study. Our goal is to achieve 0.80
> power to detect a medium effect size of 0.25 at the standard 0.05
> alpha error probability for a repeated measures factorial ANOVA.

## 15. Stopping rule

> We will post 20 new participant slots per week and monitor recruitment
> progress. If, by the end of first month after recruiting, the total
> number of participants recruited falls short of 80, we will post
> additional recruitment slots until the desired sample size is reached.

# Variables {#variables}

> In this section you can describe all variables (both manipulated and
> measured variables) that will later be used in your confirmatory
> analysis plan. In your analysis plan, you will have the opportunity to
> describe how each variable will be used. If you have variables which
> you are measuring for exploratory analyses, you are not required to
> list them, though you are permitted to do so.

## 16. Manipulated variables

> We manipulated the speed of tempo by dividing them into fast and slow
> in two levels: music with a tempo greater than 120 beats per minute
> (BPM) is considered a fast tempo, designed to evoke a high-energy,
> excited state (e.g., fast-paced rock or electronic music). Music with
> a tempo less than 60 BPM is considered a slow tempo, designed to evoke
> a calm or drowsy state (e.g., slow classical or ambient music). We
> also manipulated the energy of music by positiveness by introducing
> two levels: Music that evokes a positive emotional response, such as
> happiness, excitement, or calmness is positively valenced. Music that
> evokes a negative emotional response, such as anger, sadness, or
> tension is negatively valenced.

## 17. Measured variables

> Outcome measures: Mean reaction time will be measured in milliseconds
> (ms) from the moment a decision prompt appears to when the participant
> selects their response (either "cooperate" or "betray").

> Decision outcome will require participants to choose between two
> options in each round of the decision-making task: "cooperate" or
> "betray" under the four conditions.

> Questionnaire measures: For pleasantness, participants will rate the
> music's pleasantness on a 7-point Likert scale after each music
> condition:

> Sample question:
>
> "How pleasant did you find this piece?"
>
> (1 = Very unpleasant, 7 = Very pleasant)

> Mood will be assessed using a mood inventory that's inspired by the
> PANAS (positive and negative affect schedule) on a 5-point Likert
> scale (1 = Not at all, 5 = Extremely), assessing both positive and
> negative emotional states.

> Sample question:
>
> "To what extent did you experience the following emotions while
> listening to the background music?"
>
> Excited (1 to 5) -\> positive
>
> Determined (1 to 5) -\> positive
>
> Strong (1 to 5) -\> positive
>
> Alert (1 to 5) -\> positive
>
> Hostile (1 to 5) -\> negative
>
> Distressed (1 to 5) -\> negative
>
> Nervous (1 to 5) -\> negative
>
> Guilty (1 to 5) -\> negative

> Demographic assessments will include age, gender, region etc.
>
> Sample questions:
>
> "What is your age?" (Open-ended)
>
> "How do you identify?" (Male, Female, Non-binary / Third gender,
> Prefer not to say)
>
> "Which region are you currently living in?" (Open-ended)
>
> "Do you have formal musical training?" (Yes / No)
>
> "How often do you listen to music?" (Rarely, Occasionally, Frequently,
> Daily)

## 18. Indices

> Questionnaire measures: For pleasantness, we will take the mean of
> pleasantness ratings across all four music conditions (fast-positive,
> fast-negative, slow-positive, slow-negative). For mood, We will have a
> mood index that combines the positive and negative affect scores from
> the PANAS to create a single measure of overall mood before and after
> the task.
>
> Positive Mood Subscore (P): The sum of ratings for positive emotions
> (e.g., excited, happy, etc.). Negative Mood Subscore (N): The sum of
> ratings for negative emotions (e.g., angry, sad, etc.).

# Analysis Plan {#analysis-plan}

> You may describe one or more confirmatory analysis in this
> preregistration. Please remember that all analyses specified below
> must be reported in the final article, and any additional analyses
> must be noted as exploratory or hypothesis generating.
>
> A confirmatory analysis plan must state up front which variables are
> predictors (independent) and which are the outcomes (dependent),
> otherwise it is an exploratory analysis. You are allowed to describe
> any exploratory work here, but a clear confirmatory analysis is
> required.

## 19. Statistical models

> We will use a factorial within subjects ANOVA to analyze out results.
> The manipulated categorical independent variables are 'Tempo' and
> 'Modality' whereas the numeric dependent variable is 'mean reaction
> time' and the categorical dependent variable is 'decision outcomes'.

## 20. Transformations

> The "Effect of background music on decision-making" does not require
> any additional transformations.

> If we're using a regression analysis, music modality (Positive vs.
> Negative): could be recoded as a categorical variable with two levels:
> 0 = Positive modality, 1 = Negative modality.

> Tempo (Fast vs. Slow) could also be coded as a categorical variable
> with two levels: fast tempo will be coded as 0, slow tempo will be
> coded as 1.

## 21. Inference criteria

> We will use the standard significance level of p \< .05 for
> determining if the ANOVA and the post hoc test (Tukey HSD tests)
> suggest that the results are significantly different from those
> expected if the null hypothesis were correct. We will use one-tailed
> tests for all of our analyses, as we are predicting specific
> directional effects for both tempo and modality (valence/energy level)
> on reaction time and decision-making behavior. We can also include the
> effect size and 95% confidence interval.

## 22. Data exclusion

> Any reaction times that are below the 2.5% or above the 97.5%
> percentiles of the distribution will be considered outliers. For
> decision-making behavior (e.g., choosing "betray" vs. "cooperate"), we
> will exclude participants whose decision patterns are extremely
> inconsistent or deviate from the rest of the group, like choosing
> "betray" more than 90% of the time, regardless of condition, as this
> may indicate that they did not engage meaningfully with the task.

## 23. Missing data

> If a participant completes only some of the trials, the participant's
> data will be excluded from the analysis.

## 24. Exploratory analysis

> We expect that cultural difference may be related to the perception of
> positiveness of music. Personality would also be affecting the liking
> score of one piece, and liking the piece may also affect performances
> in the study. Therefore, we will look for relationships between these
> variables and the primary outcome measures.

# Other {#other}

## 25. Other

> **(Optional)** If there is any additional information that you feel
> needs to be included in your preregistration, please enter it here.

# References